= debug_output
:source-highlighter: coderay
:coderay-linenums-mode: inline
:toc:

C++ debug output that's get's printed, unless `NDEBUG` is defined. +
Includes mutex-protected versions, that can be used with multithreading; as well as optional filename and linenumber output.

== Three Variants

. https://github.com/ajneu/debug_output/blob/master/debug_output/debug_output_functionlike_macro_statement.h[`debug_output_functionlike_macro_statement.h`] +
 see <<statement,below>>
. https://github.com/ajneu/debug_output/blob/master/debug_output/debug_output_functionlike_macro_expression_chaining.h[`debug_output_functionlike_macro_expression_chaining.h`] +
 see <<chaining,below>>
. https://github.com/ajneu/debug_output/blob/master/debug_output/debug_output_non_functionlike_macro.h[`debug_output_non_functionlike_macro.h`] +
 see <<nonfunclike,below>>
 
The specific variant chosen is selected via
https://github.com/ajneu/debug_output/blob/master/debug_output/debug_output_selector.h[`debug_output_selector.h`] +
(which is automatically included from the main header https://github.com/ajneu/debug_output/blob/master/debug_output/debug_output.h[`debug_output.h`])

== Two Usage Choices

. **Single global variant config** (example: https://github.com/ajneu/debug_output/tree/master/ex_single_global_conf[`ex_single_global_conf`]) -- recommended!
+
* First Set defaults in https://github.com/ajneu/debug_output/blob/master/ex_single_global_conf/debug_output_user.h[`debug_output_user.h`]
* Then include top header `debug_output.h`
+
[source,cpp]
----
#include "debug_output.h" /* automatically includes debug_output_user.h and debug_output_selector.h */
----

. **Per-case variant selector** (example: https://github.com/ajneu/debug_output/tree/master/ex_per_case_selector[`ex_per_case_selector`])
+
* (same as above) First Set defaults in https://github.com/ajneu/debug_output/blob/master/ex_single_global_conf/debug_output_user.h[`debug_output_user.h`]
* (same as above) Then include top header `debug_output.h`
* But the `debug_output_user.h` defaults can be overriden on a per-case basis, by including `debug_output_selector.h`.
+
[source,cpp]
----
#include "debug_output.h" /* also includes "debug_output_user.h", and "debug_output_selector.h" */

// ...

// override settings in debug_output_user.h on a per-case basis:
#undef  DEBUG_OUTPUT_VARIANT
#define DEBUG_OUTPUT_VARIANT   DEBUG_OUTPUT_FUNCLIKE_CHAINING
#include "debug_output_selector.h"

//... 
----

Recommended is to use the single global config.

Then just use this:
[source,cpp]
----
DOUT( << "hello" << " world" << std::endl);
DERR( << "hello" << " world" << std::endl);
DLOG( << "hello" << " world" << std::endl);
----

https://github.com/ajneu/debug_output/blob/master/ex_single_global_conf/debug_output_user.h[`debug_output_user.h`] settings:

Mutex-protection:: If you are in a multithreading environment, and want the arguments in the brackets
(above it is `<< "hello" << " world" << std::endl` ) to be mutex-protected,
then just edit the settings of `debug_output_user.h`, to have `DEBUG_OUT_MUTEX_EVERY_BRACKET` defined: https://github.com/ajneu/debug_output/blob/master/ex_single_global_conf/debug_output_user.h#L33[example]
+
Filename and Linenumbers:: If you want outputs with filename and linenumbers, then just edit the settings of `debug_output_user.h`, to have `DEBUG_OUT_LINENO` defined: https://github.com/ajneu/debug_output/blob/master/ex_single_global_conf/debug_output_user.h#L44[example]


[[statement]]
== Recommended: Function-like Macro as standalone statement

Enable with `#define DEBUG_OUTPUT_FUNCLIKE_STATEMENT` +
automatically includes https://github.com/ajneu/debug_output/blob/master/debug_output/debug_output_functionlike_macro_statement.h[`debug_output_functionlike_macro_statement.h`] +

* Basic usage:
+
[source,cpp]
----
DOUT( << "hello" << " world" << std::endl); // "debug output"
----
+
You have to wrap the operators (`<<`) and their right-hand operands in brackets, since `DOUT` is a function-like macro.
+
The preprocessor then generates
+
[cols="2,1"]
|===
a|
[source,cpp]
----
std::cout << "hello " << "world" << std::endl;
----
a|if `NDEBUG` is not defined +
  (i.e. debugging, so output debug-information)
|===
+
[cols="2,1"]
|===
a|
[source,cpp]
----
/* nothing */
----
a|if `NDEBUG` is defined +
  (i.e. not debugging, so no output)
|===
+
Why wrap the operators and operands in brackets?
+
The reason: sooner or later you'll find you'll need a mutex-protected print-version, that works in a multi-threaded program and secures the global `std::cout` resource: +

* Mutex-protected usage:
+
[source,cpp]
----
DMOUT( << "hello" << " world" << std::endl); // "debug mutex out"
----
+
The macro knows how many chained operators (`<<`) and operands, are included in the scope of the mutex-protection, by requiring them to be wrapped in brackets.
+
This generates
+
[cols="2,1"]
|===
a|
[source,cpp]
----
 {                                                     \
    std::lock_guard<std::mutex> lock{debug_out_mutex}; \
    std::cout << "hello " << "world" << std::endl;     \
 }
----
a|if `NDEBUG` is not defined +
  (i.e. debugging, so output debug-information)
|===
+
[cols="2,1"]
|===
a|
[source,cpp]
----
/* nothing */
----
a|if `NDEBUG` is defined +
  (i.e. not debugging, so no output)
|===


=== Minor Limitations

Chaining out beyond the macro...
[source,cpp]
----
DOUT( << "hello " << "world" << std::endl)   << "chaining does not work";
//                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//                                          does not work (when NDEBUG defined)
----
does not work.

In other words: this specific `DOUT` can only be used as a standalone statement. +
If you want chaining, then see below <<chaining>>.

=== Implementation Details

==== Non-Mutex Version

[cols="1,2"]
|===
|
*Macro when `NDEBUG` not defined* +
(debugging, so print output)

a|
[source,cpp]
----
#ifndef NDEBUG
#define DOUT(...) (std::cout __VA_ARGS__)
#endif
----
|===


[cols="1,2"]
|===
|*Macro when `NDEBUG` defined* +
(not debugging, so print nothing)

a|
[source,cpp]
----
#ifdef NDEBUG
#define DOUT(...) /* nothing */
#endif
----
|===



==== Mutex-protected Version

[cols="1,2"]
|===
|
*Macro when `NDEBUG` not defined* +
(debugging, so print output)

a|
[source,cpp]
----
#ifndef NDEBUG
#define DMOUT(...)                                    \
 {                                                     \
    std::lock_guard<std::mutex> lock{debug_out_mutex}; \
    std::cout __VA_ARGS__;                             \
 }
#endif
----
[[mutex]]where `debug_output.h` has
[source,cpp]
----
#ifndef NDEBUG
#include <mutex>
extern std::mutex debug_out_mutex;
#endif
----
and `debug_output.cpp` has
[source,cpp]
----
#ifndef NDEBUG
#include <mutex>
std::mutex debug_out_mutex;
#endif
----
|===


[cols="1,2"]
|===
|*Macro when `NDEBUG` defined* +
(not debugging, so print nothing)

a|
[source,cpp]
----
#ifdef NDEBUG
#define DMOUT(...) /* nothing */
#endif
----
|===









[[chaining]]
== Non-recommended: Function-like Macro as expression ("chaining behaviour")

Enable with `#define DEBUG_OUTPUT_FUNCLIKE_CHAINING` +
automatically includes https://github.com/ajneu/debug_output/blob/master/debug_output/debug_output_functionlike_macro_expression_chaining.h[`debug_output_functionlike_macro_expression_chaining.h`]

The difference with the <<statement,statement version>> above, is that here the chaining behaviour of `ostream` is possible.

But this version is less efficient (in that it requires a specific global `nullout` -- <<nullstream,reference>>), so I do not recommend this version, but instead the <<statement,version already shown above>>.

* Basic usage:
+
[source,cpp]
----
DOUT(  << "hello" << " world" << std::endl) << "chain-it!"; // "debug output"
DOUT() << "greetings" << std::endl;                         // "debug output"
----

* Mutex-protected usage:
+
[source,cpp]
----
DMOUT( << "mutex " << "protected" << std::endl)    << "not mutex " << "protected" << std::endl;
//     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//            mutex protection                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//                                                             no mutex protection
----

=== Implementation Details

==== Non-Mutex Version

[cols="1,2"]
|===
|
*Macro when `NDEBUG` not defined* +
(debugging, so print output)

a|
[source,cpp]
----
#ifndef NDEBUG
#define DOUT(...) (std::cout __VA_ARGS__)
#endif
----
|===


[cols="1,2"]
|===
|*Macro when `NDEBUG` defined* +
(not debugging, so print nothing)

a|
[source,cpp]
----
#ifdef NDEBUG
#define DOUT(...) nullout
#endif
----
[[nullstream]]where `debug_output.h` has
[source,cpp]
----
#ifdef NDEBUG

#include <ostream>

/// https://groups.google.com/d/msg/comp.lang.c++/HkEffd3Geb4/g8J6yTgSyQkJ
struct Nullstream: std::ostream {
  Nullstream(): std::ios(0), std::ostream(0) {}
};

extern Nullstream nullout;

#endif /* NDEBUG */
----
and `debug_output.cpp` has
[source,cpp]
----
#ifdef NDEBUG
/// https://groups.google.com/d/msg/comp.lang.c++/HkEffd3Geb4/g8J6yTgSyQkJ
struct Nullstream: std::ostream {
  Nullstream(): std::ios(0), std::ostream(0) {}
};
Nullstream nullout;
#endif
----
|===



==== Mutex-protected Version

[cols="1,2"]
|===
|*Macro when `NDEBUG` not defined* +
(debugging, so print output)

a|
[source,cpp]
----
#ifndef NDEBUG
#define DMOUT(...)         \
(static_cast<void>         \
 (                         \
   [&](){ std::lock_guard<std::mutex> lock{debug_out_mutex}; \
          std::cout __VA_ARGS__;                             \
        }()                                                  \
 ), std::cout)

/*
/// statement expressions (seem to be a GNU extension)
#define DMOUT(...)                                    \
(({ std::lock_guard<std::mutex> lock{debug_out_mutex}; \
    static_cast<void>(std::cout __VA_ARGS__);          \
   }), std::cout)
*/
#endif /* NDEBUG */
----
with `debug_out_mutex` as shown <<mutex,above>>.
|===


[cols="1,2"]
|===
|*Macro when `NDEBUG` defined* +
(not debugging, so print nothing)

a|
[source,cpp]
----
#ifdef NDEBUG
#define DMOUT(...) nullout
#endif
----
with `nullout` as shown <<nullstream,above>>
|===







[[nonfunclike]]
== Non-recommended: Macro (but not function-like)

Enable with `#define DEBUG_OUTPUT_NON_FUNCLIKE` +
automatically includes https://github.com/ajneu/debug_output/blob/master/debug_output/debug_output_non_functionlike_macro.h[`debug_output_non_functionlike_macro.h`]

If you really desperately want this +
[source,cpp]
----
D_OUT << "hello" << " world" << std::endl;
----
i.e. no wrapping in brackets (and really don't need mutex-protection)... +
then see this method (adapted from here http://stackoverflow.com/a/11826787 )

[cols="1,2"]
|===
|*Macro when `NDEBUG` not defined* +
(debugging, so print output)

a|
[source,cpp]
----
#ifndef NDEBUG
#define D_OUT (std::cout)
#endif
----
|===




[cols="1,2"]
|===
|*Macro when `NDEBUG` defined* +
(not debugging, so print nothing)

a|
[source,cpp]
----
#ifdef NDEBUG
#define D_OUT             \
  if (debug_disabled)    \
  { /* nothing */        \
  }                      \
  else                   \
    Nullstream()    
#endif
----
With header `debug_output.h` having:
[source,cpp]
----
#ifdef NDEBUG
constexpr bool debug_disabled{true};

struct Nullstream: std::ostream {
  Nullstream(): std::ios(0), std::ostream(0) {}
};
#endif
----

|===
